#自定义配置
arb:
  service:
    name: phoenix-WEB
    port: 8080

---
eureka:
  instance:
    instance-id: ${arb.service.url}:${spring.application.name}:${server.port}
    hostname: ${arb.service.url}
    ip-address: ${arb.service.url}
    prefer-ip-address: true
  #    lease-renewal-interval-in-seconds: 10
  #    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://${arb.eureka.url}:8901/eureka/
server:
  port: ${arb.service.port}
  max-http-header-size: 10240000
  tomcat:
    max-http-post-size: -1
spring:
  application:
    name: ${arb.service.name}
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: -1
      max-request-size: -1
---
spring:
  profiles: local
arb:
  eureka:
    url: 192.168.0.100
  service:
    url: 127.0.0.1
#  redis:
#    host: china-dev.vertical.arbcalls.com
#    port: 6379
#    password: arbfintech
#    timeout: 1000
#    pool:
#      max-active: -1

#logging:
#  config: classpath:log4j2.yml




