server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ericssion2019/config-leaning.git
          search-paths: config-repository
          username: Ericssion2019
          password: sichao2019
